#!/usr/bin/env python3
"""emit_beamer.py — the deterministic BACKEND of the paper2beamer compiler.

Role in the pipeline: render a finalised ``ir.v4.json`` (the slide plan) into a
``deck.tex`` that uses the bundled *Simple* Beamer theme. This stage is a **pure
function of the IR** — it makes zero semantic decisions. Every "what goes on a
slide" choice was already made by the layout-pass; the backend only knows how to
spell those choices in LaTeX, exactly like an LLVM target backend knows the ISA
but not the program's intent.

Why a separate, dumb backend? Determinism. The same IR always yields the same
``.tex``, which makes the output testable with a golden file and keeps LaTeX
syntax mistakes out of the LLM's hands.

Usage (stdlib only — no third-party deps, runs under plain python or uv)::

    python paper2beamer/scripts/emit_beamer.py --ir build/ir.v4.json --out build/deck.tex

Defensive posture:
  * The IR is validated (stage "layout-pass") before a single byte is emitted.
  * All paper-derived text is escaped via ir_common.escape_latex.
  * ``width`` values are whitelisted against an injection-safe pattern.
  * A figure whose image file is missing degrades to a labelled placeholder box
    instead of crashing the LaTeX build.
"""

from __future__ import annotations

import argparse
import os
import re
from typing import Any

import ir_common
from ir_common import escape_latex, eprint, die


# ---------------------------------------------------------------------------
# Safety whitelists
# ---------------------------------------------------------------------------

#: A LaTeX width must look like ``0.7\textwidth`` / ``\linewidth`` / ``5cm``.
#: Anything else is rejected and replaced with the default, so a malformed (or
#: malicious) IR cannot inject arbitrary TeX through the width field.
_WIDTH_RE = re.compile(r"^(?:\d+(?:\.\d+)?)?\\(?:text|line|column)width$|^\d+(?:\.\d+)?(?:pt|cm|mm|in|em|ex)$")
_DEFAULT_WIDTH = r"0.8\textwidth"


def _safe_width(value: Any) -> str:
    if isinstance(value, str) and _WIDTH_RE.match(value.strip()):
        return value.strip()
    return _DEFAULT_WIDTH


#: Occasion -> title-page eyebrow label. Falls back to a neutral default.
_EYEBROW_BY_OCCASION = {
    "conference": "CONFERENCE TALK",
    "journal-club": "JOURNAL CLUB",
    "defense": "THESIS DEFENSE",
    "lab-meeting": "LAB MEETING",
}
_DEFAULT_EYEBROW = "PAPER READING DECK"

#: Short talks get tighter type; threshold chosen to match the theme's "dense"
#: intent (result-heavy decks under ~15 min).
_DENSE_DURATION_MIN = 15


# ---------------------------------------------------------------------------
# Preamble
# ---------------------------------------------------------------------------

def _theme_options(intent: dict[str, Any]) -> str:
    eyebrow = _EYEBROW_BY_OCCASION.get(str(intent.get("occasion", "")), _DEFAULT_EYEBROW)
    duration = intent.get("duration_min", 30)
    density = "dense" if isinstance(duration, (int, float)) and duration <= _DENSE_DURATION_MIN else "normal"
    # overflowguard=on turns the LaTeX build into the pipeline's verifier: a frame
    # that grows into the footer stops the build with a clear error, which the
    # SKILL.md verifier loop feeds back into the layout-pass.
    return f"eyebrow={{{escape_latex(eyebrow)}}},density={density},overflowguard=on"


def _render_preamble(ir: dict[str, Any]) -> list[str]:
    paper = ir["paper"]
    intent = ir["intent"]
    title = escape_latex(paper.get("title", "Untitled"))
    authors = paper.get("authors") or []
    author = escape_latex(", ".join(authors)) if authors else escape_latex("Unknown author")
    institute = escape_latex(paper.get("venue", ""))
    # A short title keeps the footer from clipping (theme manual guidance).
    short_title = escape_latex((paper.get("title", "Untitled") or "")[:40])

    lines = [
        "% Generated by paper2beamer emit_beamer.py — do not edit by hand.",
        "% Re-run the backend to regenerate from the IR.",
        r"\documentclass[aspectratio=169]{beamer}",
        f"\\usetheme[{_theme_options(intent)}]{{Simple}}",
        r"\usepackage{booktabs}  % nicer tables if the deck includes any",
        r"\usepackage{graphicx}",
        # figures/ holds the cropped originals; ./ lets the deck find the theme.
        r"\graphicspath{{figures/}{./}}",
        "",
        f"\\title[{short_title}]{{{title}}}",
        f"\\author{{{author}}}",
    ]
    if institute:
        lines.append(f"\\institute{{{institute}}}")
    lines += [
        r"\date{}",
        "",
        r"\begin{document}",
        "",
    ]
    return lines


# ---------------------------------------------------------------------------
# Frame rendering
# ---------------------------------------------------------------------------

def _render_items(items: Any, env: str) -> list[str]:
    """Render an itemize/enumerate list. Empty lists are skipped by the caller."""
    out = [f"  \\begin{{{env}}}"]
    for item in items:
        out.append(f"    \\item {escape_latex(item)}")
    out.append(f"  \\end{{{env}}}")
    return out


def _render_block(item: dict[str, Any]) -> list[str]:
    """Render a block/alertblock/exampleblock or a bare itemize/enumerate."""
    kind = item["block"]
    if kind in ("itemize", "enumerate"):
        return _render_items(item.get("items") or [], kind)

    title = escape_latex(item.get("title", ""))
    out = [f"  \\begin{{{kind}}}{{{title}}}"]
    # A block may carry a paragraph ("text") and/or bullet "items".
    text = item.get("text")
    if text:
        out.append(f"    {escape_latex(text)}")
    items = item.get("items") or []
    if items:
        out.append(r"    \begin{itemize}")
        for it in items:
            out.append(f"      \\item {escape_latex(it)}")
        out.append(r"    \end{itemize}")
    out.append(f"  \\end{{{kind}}}")
    return out


def _render_figure(item: dict[str, Any], figures_by_id: dict[str, dict[str, Any]],
                   out_dir: str) -> list[str]:
    """Embed an original figure by id, or a placeholder if its file is missing."""
    fid = item["figure"]
    fig = figures_by_id.get(fid)
    width = _safe_width(item.get("width"))
    # Caption precedence: explicit slide caption > original paper caption > none.
    caption = item.get("caption")
    if caption is None and fig is not None:
        caption = fig.get("caption", "")
    caption_tex = escape_latex(caption or "")

    rel_path = fig.get("path") if fig else None
    abs_path = os.path.join(out_dir, rel_path) if rel_path else None

    out = [r"  \begin{figure}", r"    \centering"]
    if rel_path and abs_path and os.path.isfile(abs_path):
        # includegraphics resolves rel_path against \graphicspath / deck.tex dir.
        out.append(f"    \\includegraphics[width={width},height=0.55\\textheight,keepaspectratio]{{{rel_path}}}")
    else:
        # Degrade gracefully: a visible placeholder beats a hard LaTeX failure,
        # and tells the user exactly which asset to restore.
        eprint(f"  warn: figure {fid!r} image missing ({rel_path!r}); emitting placeholder")
        missing = escape_latex(f"[missing figure: {fid}]")
        out.append(f"    \\fbox{{\\parbox[c][0.45\\textheight][c]{{{width}}}{{\\centering {missing}}}}}")
    if caption_tex:
        out.append(f"    \\caption{{{caption_tex}}}")
    out.append(r"  \end{figure}")
    return out


def _render_body(body: Any, figures_by_id: dict[str, dict[str, Any]],
                 out_dir: str) -> list[str]:
    out: list[str] = []
    for item in body or []:
        if "figure" in item:
            out += _render_figure(item, figures_by_id, out_dir)
        elif "block" in item:
            out += _render_block(item)
        # validate_ir already guaranteed one of the two keys exists.
    return out


def _render_slide(slide: dict[str, Any], figures_by_id: dict[str, dict[str, Any]],
                  out_dir: str) -> list[str]:
    ftype = slide["frame_type"]
    if ftype == "titleframe":
        return [r"\titleframe", ""]
    if ftype == "statementframe":
        return [f"\\statementframe{{{escape_latex(slide['text'])}}}", ""]
    if ftype == "thanksframe":
        head = slide.get("headline")
        sub = slide.get("subtitle")
        cmd = r"\thanksframe"
        if head:
            cmd += f"[{escape_latex(head)}]"
        if sub:
            # Beamer optional args are positional: a subtitle needs a headline slot.
            if not head:
                cmd += "[Thank you]"
            cmd += f"[{escape_latex(sub)}]"
        return [cmd, ""]

    # Ordinary content frame.
    title = escape_latex(slide["title"])
    notes = slide.get("notes")
    out = [f"\\begin{{frame}}{{{title}}}"]
    out += _render_body(slide.get("body", []), figures_by_id, out_dir)
    out.append(r"\end{frame}")
    if notes:
        # Speaker notes live alongside the frame; harmless if \setbeameroption
        # isn't enabled, valuable when the user turns notes on.
        out.append(f"\\note{{{escape_latex(notes)}}}")
    out.append("")
    return out


# ---------------------------------------------------------------------------
# Top level
# ---------------------------------------------------------------------------

def render(ir: dict[str, Any], out_dir: str) -> str:
    """Render a validated IR into a complete LaTeX document string."""
    figures_by_id = {f["id"]: f for f in ir.get("figures", [])}
    lines = _render_preamble(ir)
    for slide in ir["slides"]:
        lines += _render_slide(slide, figures_by_id, out_dir)
    lines.append(r"\end{document}")
    return "\n".join(lines) + "\n"


def run(ir_path: str, out_path: str) -> str:
    ir = ir_common.load_ir(ir_path)
    # The backend only accepts a fully-formed slide plan. Validating here means a
    # malformed IR is reported in terms of IR fields, never as opaque TeX errors.
    ir_common.validate_ir(ir, stage="layout-pass")
    out_dir = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(out_dir, exist_ok=True)
    tex = render(ir, out_dir)
    # Atomic write so a partial deck.tex never reaches latexmk.
    tmp = out_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(tex)
    os.replace(tmp, out_path)
    eprint(f"backend: wrote {out_path} ({len(ir['slides'])} slides)")
    return out_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render ir.v4.json -> deck.tex (Simple theme).")
    parser.add_argument("--ir", required=True, help="path to ir.v4.json (slide plan)")
    parser.add_argument("--out", required=True, help="output deck.tex path")
    args = parser.parse_args(argv)
    try:
        run(args.ir, args.out)
    except ir_common.IRValidationError as exc:
        die(f"IR validation failed -> {exc}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
